<?php

/**
 * Implements hook_ENTITY_TYPE_insert().
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function ib_task_93_node_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $get_title_array = $entity->get('title')->getValue();
  $node_title = NULL;

  foreach ($get_title_array as $value) {
    foreach ($value as $title) {
      $node_title = $title;
    }
  }

  $country = \Drupal::config('ib_task_93.settings')->get('ib_task_93_country');
  $entity->setTitle($node_title . " " . $country);
}
