<?php

/**
 * @file
 * File for custom token hooks.
 */

use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_token_info().
 */
function ib_task_80_token_info() {
  return [
    'types' => [
      'custom' => [
        'name' => t('custom'),
        'description' => t('custom token'),
      ],
    ],

    'tokens' => [
      'custom' => [
        'link_to_google' => [
          'name' => t('link_to_google'),
          'description' => t('custom token'),
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_tokens().
 */
function ib_task_80_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];

  if ($type == 'custom') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'link_to_google':
          $replacements[$original] = 'http://google.com';
          break;
      }
    }
  }

  return $replacements;
}
